# Generated by Django 3.0.4 on 2020-03-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200320_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextradetails',
            name='user_project_completed',
            field=models.IntegerField(default=0),
        ),
    ]
