# Generated by Django 3.0.4 on 2020-03-21 22:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200320_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(upload_to=users.models.PathAndRename('pics/2020/03/21')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_image',
            field=models.ImageField(default='media/default.png', upload_to=users.models.PathAndRename('profile/2020/03/21')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_resume',
            field=models.FileField(default='media/resume.pdf', upload_to=users.models.PathAndRename('files/2020/03/21')),
        ),
    ]
