# Generated by Django 3.0.4 on 2020-03-24 03:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200323_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='award_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='college_end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='college_start_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_end_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_start_year',
        ),
        migrations.AddField(
            model_name='award',
            name='award_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='college_end_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='college_start_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='end_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_end_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_start_month_year',
            field=models.CharField(default='month,year', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(upload_to=users.models.PathAndRename('pics/2020/03/24')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to=users.models.PathAndRename('profile/2020/03/24')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_resume',
            field=models.FileField(default='resume.pdf', upload_to=users.models.PathAndRename('files/2020/03/24')),
        ),
    ]
