# Generated by Django 3.0.4 on 2020-03-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200324_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_photo',
            new_name='project_image',
        ),
    ]
