# Generated by Django 3.0.4 on 2020-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200324_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
