# Generated by Django 3.0.4 on 2020-03-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200325_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='user_linkedin',
            new_name='contact_profile_url',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='user_twitter',
            new_name='contact_type',
        ),
    ]
