# Generated by Django 3.0.4 on 2020-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200325_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_type',
            field=models.CharField(max_length=20),
        ),
    ]
