# Generated by Django 3.0.4 on 2020-03-28 00:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200325_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_month_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_month_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to=users.models.PathAndRename('pics/2020/03/28')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to=users.models.PathAndRename('profile/2020/03/28')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_resume',
            field=models.FileField(default='resume.pdf', upload_to=users.models.PathAndRename('files/2020/03/28')),
        ),
    ]
