# Generated by Django 3.0.3 on 2020-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.TextField(default='XYZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=4),
        ),
    ]
