# Generated by Django 3.0.3 on 2020-03-07 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200307_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='desc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
