# Generated by Django 3.0.3 on 2020-03-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200307_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='desc',
            field=models.TextField(),
        ),
    ]
