# Generated by Django 3.0.3 on 2020-03-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200307_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('award_place', models.CharField(max_length=100)),
                ('describe_award', models.TextField()),
                ('award_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=200)),
                ('publication_name', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('publication_url', models.URLField()),
                ('publication_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField()),
                ('percentage_you_know', models.ImageField(upload_to='')),
            ],
        ),
    ]
