# Generated by Django 3.0.3 on 2020-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200308_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percentage_you_know',
            field=models.IntegerField(),
        ),
    ]
