# Generated by Django 3.0.3 on 2020-03-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200308_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_url', models.URLField()),
                ('project_photo', models.ImageField(upload_to='pics')),
                ('project_start_year', models.CharField(max_length=4)),
                ('project_end_year', models.CharField(max_length=4)),
            ],
        ),
    ]
