# Generated by Django 3.0.4 on 2020-03-19 04:28

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(upload_to=portfolio.models.PathAndRename('pics/2020/03/19')),
        ),
    ]
